version: '3.1'

services:

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: passw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "G:/Docker/volumes/flashcards/db:/custom/mount:/var/lib/postgresql/data"
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080